import mongoose from "mongoose";

const hotel_infosModel= new mongoose.Schema({
    Address: String,
    State: String,
    City: String,
    Country: String,
    Email: String,
    Check_In: String,
    Check_out: String,
    Contact_Name: String,
    Floor_Number: String,
    Hotel_Description: String,
    Hotel_Id: Number,
    Hotel_Type: String,
    Hotel_name: String,
    Official_Category: String,
    Phone_Number: String,
    Pin_Code: Number,
    rating: String,
    user_review_count: Number,
    is_review_available: String,
    hour3_display_flag: Number,
    final_display_price_for_3H: Number,
    hour6_display_flag: Number,
    final_display_price_for_6H: Number,
    hour12_display_flag: Number,
    final_display_price_for_12H: Number,
    hour24_display_flag: Number,
    final_display_price_for_24H: Number,
    Location: String,
    hotel_category: String,
    facilities : Array,
    staff_behaviour : String,
    smooth_check_in : String,
    room_quality : String,
    hotel_surroundings : String,
    policy : Array,
    cancellation_policy : Array,
    latitude : String,
    longitude : String,
    status : String,      
    place_desc : String,
    guest_place : String,
    reception_number: String,
    secondary_email: String,
    lease_expiry_date: String,
    closing_description: String,
});

export const Hotel_Infos = mongoose.models.hotel_infos || mongoose.model("hotel_infos",hotel_infosModel)